source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'bootstrap-sass','>= 2.3.0.0'
  gem 'jquery-rails'
  gem 'haml-rails'
end

group :development, :test do
  gem 'html2haml'
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'email_spec'
  gem 'rspec-rails'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
end

gem "unicorn", ">= 4.3.1"
gem "figaro", ">= 0.6.3"
